apiVersion: v1
kind: Secret
metadata:
  name: {{ include "curl.fullname" . }}
  labels:
    {{- include "curl.labels" . | nindent 4 }}
type: Opaque
data:
  SENDER_MAIL_USERNAME: {{ .Values.mail.sender | b64enc }}
  SENDER_MAIL_PASSWORD: {{ .Values.mail.password | b64enc }}
  RECEIVER_MAIL_ADDRESS: {{ .Values.mail.reciever | b64enc }}